### PR TITLE
extract glew, eigen as external libraries in build

### PR DESCRIPTION
**Pull request by wilhelmtell**
* mv src/VPaint.pro VPaint.pro
 * VPaint.pro is of template subdirs
 * mv src/ app
 * add subproject app/app.pro
 * mv src/Eigen src/GLEW lib/
 * add subproject lib/GLEW/glew.pro
 * change `#include "../Eigen/Core"` to `#include <Eigen/Core>`

express external libraries as such in the build, so crucial warnings are
heard.

eigen and glew are not part of the project. they are dependencies,
external libraries. any warnings coming out of there are not interesting
as far as this project is concerned, because only developers of those
projects can fix them. what's worse is warnings coming from external
libraries flood and hide relevant and interesting warnings coming from
code of this project.

### CODE REVIEW

**Comment by wilhelmtell** [comment]
So, to re-cap: what I wanted to do is contrast VPaint compiler warnings from compiler warnings coming from external libraries. The reason is that I want to know about every single warning the compiler points out, but not if this is a warning coming from external libraries, because I don't intend to fix any of these here.

The approach I've taken here is to change the VPaint.pro project file from being of an app template to be of a subdirs template. If you create a new Qt Creator project, one of the project templates is a subdirs template: this allows creating a project with subprojects. It's useful for separating logic from gui and also for separating libraries, I figure.

So, the VPaint.pro file, being of subdirs template, can't do anything other than point at its subprojects. So I moved it to the root directory.

Then I added a lib/ directory to host the external libraries. Now there are two subprojects: app and glew. There is no need for a subproject for eigen because there is nothing to do there in terms of build: it's header-only. But I did place eigen in lib/, lib/ is now in the system include path.

I've added a project setting to the app project to `-isystem` include the stuff under lib/. This so GCC doesn't emit warnings for headers in that directory.

What used to be the src/ directory is now the app/ directory. I wouldn't have done that if it weren't for Qt Creator requiring the .pro file name to be the same name as its directory. If I wouldn't rename it, VPaint.pro would have a subproject called src, in file src/src.pro. I thought it would be more meaningful to have a subproject named app. Is it okay?

Finally, because the stuff under lib/ is now system includes, the code includes it with angle brackets, like `#include <Eigen/Core>`, to emphasize this is a system include and avoid uninteresting warnings coming from that.

**Comment by wilhelmtell** [comment]
Added a fix for the target name. The subproject app.pro produced target app.app. Oops. Should be VPaint.app.

**Comment by scribblemaniac** [comment]
Looks good to me :+1:

You should update the readme to reflect your changes.

**Comment by wilhelmtell** [comment]
True, thanks. I think the only change I needed was referring to VPaint.pro and not src/VPaint.pro, in the build instructions. So that's done.

**Comment by scribblemaniac** [comment]
Shouldn't there also be some instructions on installing Eigen to the proper place?

**Comment by wilhelmtell** [comment]
Eigen is in the repository. When you clone VPaint you get Eigen inside. There's nothing to do about Eigen or glew past cloning VPaint.

**Comment by scribblemaniac** [comment]
Okay yes, I see that now sorry. Is there any reason why you are having it build outside of the git directory?

**Comment by wilhelmtell** [comment]
I've noticed that. I didn't explicitly do anything to set that. I think that's a default behaviour, to build in the parent directory of the .pro file. Previously the project file was inside the src/ directory, and now (the main project file is) in the root directory.

**Comment by scribblemaniac** [comment]
I can't seem to find any way to change this in the .pro file. [This solution](https://stackoverflow.com/questions/2944069/how-do-i-change-the-build-output-directory-in-qt-creator?lq=1) works, however we are unable to distribute .user files so everyone who wants a different behavior would have to change it themselves.

**Comment by wilhelmtell** [comment]
I don't think it matters. I think where to place the build directory is a personal thing that a user should pick for themselves, and it shouldn't be coded into the distribution. It's as personal a choice as what compiler to use (so long as the compiler fulfills the requirements of our code -- say, C++11, or C++14 nudge-nudge :) ).

To motivate,

 * CMake places its residue in the current directory. This allows a user to decide for themselves where the build residue ought to be changing to whatever directory they want and building from there.
 * Autoconf and automake too output their residue in the current directory for the same reason.

In all cases though this means we have to be careful in the project files not to assume we know exactly where a build residue is. Here we link against libGLEW.a, but we don't know where that library will be exactly. So we have to say something like `-L $$OUT_PWD/../lib/GLEW/` so that the compiler finds the library at link-time in the library's build directory, wherever that is.

**Comment by scribblemaniac** [comment]
While it is a personal thing and users should be able to configure it to their personal preference, I doubt that anyone is expecting the build to be outside of their working directory without running `make install` or something along those lines. In my mind the repository should be as self-contained as is reasonably possible.

**Comment by wilhelmtell** [comment]
Well I for example like to keep the source tree clean from anything but stuff I intend to commit...

I don't think this is worth a hassle to work on enforcing something that the build system encourages not to enforce.

**Comment by dalboris** [comment]
Thx @wilhelmtell for this work, it's great! I think it is a really good idea to separate into projects like that, sorry for not getting back sooner, I just didn't have the time. I just have one comment, that would also solve @scribblemaniac concern about build outside the repository. Instead of:

..VPaint.pro
..lib/
....Eigen/
....GLEW/
......glew.pro
..app/
....app.pro

I would personally prefer this:

..scr/
....VPaint.pro
....Eigen/
....GLEW/
......GLEW.pro
....Gui/
......Gui.pro

This way, all the compiled source code (including third-party libraries, and the .pro files) is still under a "src" directory, which I think makes sense. What you called "app" now becomes "Gui", which I believe is a better name, since "app" is rather vague, and arguably external libraries are parts of the app. Arguably, it may makes sense to nest Eigen and GLEW under src/lib, but I think that's an overkill, and that keeping the structure minimalist makes for better clarity.

In any case, I think changing the "Eigen/..." into <Eigen/...> is much, much better than before, thx!

What do you think of these modifications, do they make sense to you as well?

**Comment by wilhelmtell** [comment]
This pull request includes a change in app.pro that declares the external libraries' headers as system includes:

    QMAKE_CXXFLAGS += ... $$QMAKE_CFLAGS_ISYSTEM $$PWD/../lib

This roughly translates to adding `-isystem /Users/me/vpaint/app/../lib` when running the compiler. In the case where glew and eigen reside in the same directory as the project's code, you'd have `-isystem /Users/me/vpaint/src/..` which implies the project's source code is reachable from the system include path. So, you could then say

    #include <gui/EditCanvasSizeDialog.h>

If on the other hand gui/ is not reachable from the system include path then the above line would give the user a compiler error. I think that generally local includes (that is, project includes, as opposed to includes that reach an external library) should be with double quotes:

    #include "EditCanvasSizeDialog.h"

to communicate that it's part of the project, both to a programmer reading the code and to the compiler that's looking for warnings to generate.

**Comment by dalboris** [comment]
Indeed, I forgot about this, then nesting those third-party library makes sense, what about:

..scr/
....VPaint.pro
....Third/
......Eigen/
......GLEW/
........GLEW.pro
....Gui/
......Gui.pro

It's equivalent of what you have, except renaming lib->Third, and app->Gui, and nesting everything under src/. It might seem that nesting under src is useless, but I prefer to keep it that way. One reason is that later, we might want to refactorize VectorAnimationComplex outside Gui, so it would be:

..scr/
....VPaint.pro
....Third/
......Eigen/
......GLEW/
........GLEW.pro
....VectorAnimationComplex/
......VectorAnimationComplex.pro
....Gui/
......Gui.pro

Makes sense?

**Comment by dalboris** [comment]
Thx! 

Though, it didn't compile (at least on Linux), since you renamed `Eigen` to `eigen`, thus the `#include <Eigen/...> ` failed. I added a commit to fix this by renaming to the letter case convention I'm using throughout the project. Now the structure is:

    src
      Third
        GLEW
        Eigen
      Gui

I didn't have any warning with g++ 4.9.2

**Pull request merged**
