### PR TITLE
Changes for 1.6

### PR DESCRIPTION
**Pull request by scribblemaniac**
So much for not making another PR :blush:

I thought I would test things out on my system before you officially make a 1.6 release to make sure everything works for me. Scaling, rotating, and a save prompt on exit all work perfectly. There was a very minor compilation error which I have fixed.

I also spotted a pretty stupid error with the update checker. Basically because the config version number was being used and not updated, whenever someone actually updated VPaint, the messages would continue to display. That is fixed now as well.

I was experimenting with the displaying background images, and I decided to implement a quick new option for it: repeat. As you may guess, it just repeats the image sequence. It does not affect missing frames within the frame range. As I've commented in the code, there's probably a better way to do the looping before the minFrame_ (lines 305 and 340 in Background.cpp), but I'm not all that good with modulus arithmetic so I'll leave that to you to see if it can be improved.

Also I have a quick question that I came up with while writing this description. Are the paths for background images handled in a cross-platform way? I don't really have any easy way to test this myself, but I just imagine that it could be an issue since a relative path on linux would be `folder/example.png` and the same path on windows would be `folder\example.png`.

### CODE REVIEW

**Comment by dalboris** [comment]
Thx for the testing! I'll test and integrate the compile error fix and the "version not updating". 

Though, the repeat option you suggest will not make it for 1.6, as it needs more work and thinking, and it's too late now. One thing obviously missing is that it isn't saved in the *.vec. But more generally, it needs more thoughts in terms of design and I am missing the time, I have to move on to the next step for my PhD work. ;)

As for your question: yes, the background path is cross-platform. It always appears as  `folder/example.png` in the GUI, and is saved as `folder/example.png` in the *.vec file, even on Windows. Then Qt is smart enough, on Windows, to internally convert the "/" into "\" when resolving the path to open and display the image.

**Comment by scribblemaniac** [comment]
That's fine I suppose, there isn't a big rush for that feature. However I think if you're really just overthinking things. I forgot to add a save, but it should just be a matter of adding another attribute in `Background::write` and `Background:read`. It isn't some major change, it's pretty much a slight modification of the hold option that you have already implemented. Worst case scenario, it shows frames outside of the given frame range in the wrong order when the repeat option is selected. I suppose you could get an index out of range error if I screwed up one of the formulas, and if you're paranoid about that, just mod the result with the array length and take the absolute value, or use `QVector::at` and catch errors.

**Comment by dalboris** [comment]
Nope, unfortunately it is more complex than that. Adding the feature means changing the file format specification. And that requires careful thinking and design that cannot be done at the last minute, since changing the file format later would be more complex.

**Comment by scribblemaniac** [comment]
Whatever, the code's not going anywhere so leave it for the next version.

**Pull request merged**
