### PR TITLE
Make it compilable on Mac using standard clang

### PR DESCRIPTION
**Pull request by Wilhansen**
It doesn't compile on the mac mainly because libc++ is not used (which is enabled if c++ is enabled via `CONFIG` and not `QMAKE_CXXFLAGS`)
Also, the change to the custom allocator is based on: http://en.cppreference.com/w/cpp/memory/allocator/construct (I don't know if it will have adverse effect on deallocation though)

### CODE REVIEW

**Comment by dalboris** [comment]
Thx!

I agree with the changes to the .pro file.

But is the change to the custom allocator necessary to make it compile with clang? This is a file from the Eigen library I use, which is very well supported and cross platform. I trust these guys and prefer not to mess up with these files, they do very smart and subtle stuff and there shouldn't ever be a need to change these files. :-)

**Comment by Wilhansen** [comment]
I see, the reason for the change is because an allocator for type `T` must be prepared to allocate for type `linked_list_node<T>` when placed in a container... which the current allocator does not do (GCC probably did something and the side effect is that certain parts are not using the custom allocator to allocate some object... the details I won't bother).

In any case, I'll double check on this and get back at you.

**Comment by Wilhansen** [comment]
I double-checked the same part in the Eigen repository, it's a know bug as listed here: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=503 and it's fixed as of March 2014: https://bitbucket.org/eigen/eigen/commits/f5b7700fef827f51d987ebab56607fbeb909e9ac

So updating Eigen might help. I tried replacing the Eigen in the source with the latest one in their website (3.2.5) and it compiles fine.

**Comment by wilhelmtell** [comment]
I think that even if there is room for that change in the allocator, if it's a change in Eigen code then you should submit it to them. Changing external libraries here can cause a headache later when you want to update the libraries.

**Comment by dalboris** [comment]
Thx guys for the investigation. Wilhelmtell is spot on: don't want to change the Eigen files within VPaint as it should be changed again when upgrading to newer version of Eigen. If Eigen already fixed this, that super good news! Thus, I'll upgrade to the latest version, make some tests to make sure it didn't break anything (probably not, but better be careful), then commit the library change.

**Comment by dalboris** [comment]
Hi Wilhansen! I've upgraded myself to 3.2.5, added the CONFIG += c++11 to the project file, and pushed to master. I didn't do the change in the Eigen/Memory.h file. Can you check if it compiles with clang now? Thank you!

**Comment by Wilhansen** [comment]
It compiles and runs fine. Thanks!

**Pull request closed without merging**
