### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by scribblemaniac**
Since pulls don't seem to be getting merged at the moment, I thought I would open this pull request for any small fixes/improvements I make. They can be merged in whenever.

### CODE REVIEW

**Comment by dalboris** [comment]
Thanks, this is awesome! I haven't looked into details though. 

After thinking a little, I may consider postponing the core-rewrite changes to VPaint 1.8, and integrating these changes (together with other small fixes and easy-to-implement features) into VPaint 1.7 instead. This, way, users won't have to wait so long before having these fixes. :)

**Comment by scribblemaniac** [comment]
You could have a 1.6.1 instead. I think it would be appropriate since it would have relatively minor changes.

**Comment by dalboris** [comment]
Hi @scribblemaniac! Update: decision making was hard, but I decided to put the core-rewrite branch on hold. I'm actually very happy with the direction it's going, but I have to move on with my research, and unfortunately I can't wait anymore for refactoring to be finished. So I'll perform my research with the "old" code (VPaint 1.6). This means I will be implementing a bunch on features which I'll merge to master in the coming months. I'll update the roadmap when I have a clearer idea, but there should be a VPaint 1.7, and even probably a VPaint 1.8, before the core-rewrite branch is merged.

Since I'm now working back from VPaint 1.6, I looked at your code and merged it. I really like the changes! :) I trust you on the "tool cursors" bug, I didn't notice it ;) You can open the pull request again if you keep implementing new stuff on this branch, or just open new ones, as you prefer.

**Comment by scribblemaniac** [comment]
Thanks for the update! I'm sure it was a tough decision but as long as some progress is being made, I'm happy with whatever you're working on. I'll keep my eye on the roadmap, but unfortunately I am extremely busy this summer, so there probably won't be too much help from me in the next couple months.

**Comment by dalboris** [comment]
Alright, I just updated the roadmap! Thanks for the heads up for this summer. Anyway, I'll mostly focus on my research stuff so not being distracted by other features might actually be better ;-)

**Pull request merged**
