### PR TITLE
Remove SettingsDialog

### PR DESCRIPTION
**Pull request by wilhelmtell**
The `SettingsDialog` class is dead code. It has one reference in class `Global` where a function instantiates and shows the dialog, and that function is called in one commented-out spot in `MainWindow`.

It's best to remove as much code as possible. Code is the source of all bugs. But also, commented-out code is overwhelming and mentally tiring. It might not seem like it, but this is a thing that accumulates over time. It has effects. When you have one file with 25 lines of code, and another with 500 lines of code, of which 475 are commented-out code, the latter is more discouraging and tiring to even look at. Even if the two are perfectly equivalent as far as the compiler is concerned.

For the it-might-be-useful-one-day syndrome, there's Git. No worries.

[Alt Bring out yer dead](https://www.youtube.com/watch?v=grbSQ6O6kbs)

### CODE REVIEW

**Comment by wilhelmtell** [comment]
I forgot to mention: this branch is based on my [topic/rm_external_libraries](https://github.com/wilhelmtell/vpaint/tree/topic/rm_external_warnings) branch.

**Comment by wilhelmtell** [comment]
And, I figure, the reason why the dialog is not used is because this functionality is delivered in a toolbar.

**Comment by dalboris** [comment]
Except that this one will very very soon be uncommented and used ;-) Sorry, but commenting/uncommenting is faster than removing, commiting, then pulling back from git. :-)

**Comment by dalboris** [comment]
Please disregard the commit above, I just entered the wrong issue number.

**Pull request closed without merging**
