### PR TITLE
Shlomif typos corrections

### PR DESCRIPTION
**Pull request by shlomif**
Some corrections for typos in the README.

### CODE REVIEW

**Comment by dalboris** [comment]
Thx! Though, can you change back to "running on "MacBook Pro 15-inch Early 2008"". Your version sounds better, but in fact, "MacBook Pro 15-inch Early 2008" is the specific model name, as appearing in " About my Mac" from the Apple menu. Thank you!

**Comment by shlomif** [comment]
@dalboris: done, thanks for the comment!

**Comment by dalboris** [comment]
Thx, very appreciated!

**Comment by shlomif** [comment]
@dalboris: you're welcome and thank you for merging it.

**Pull request merged**
