### PR TITLE
Improved mac app bundle

### PR DESCRIPTION
**Pull request by scribblemaniac**
There's been too much talk lately, it's about time we see some code! :smile: 

This commit only affects the Mac version of VPaint. It created a custom Info.plist with far more information on the application. It added support for drag and drop functionality (on the app icon on Macs only) as well as the Open with features on mac. Files with the .vec extension will now automatically open with VPaint, and they now have a shiny new icon to identify them as VPaint files. The svg icon is currently not in use, it was made for when VPaint adds support for svg importing. Some minor refactoring had to be done because the about dialog was blocking the `doOpen` slot.

The next step to improving mac support would be to add plugins for Quick Look and dynamically generated file icons. I have no idea how to do this and it is fairly low on my personal list of priorities.

### CODE REVIEW

**Comment by dalboris** [comment]
Thx! I'll check that out later today.

**Comment by dalboris** [comment]
Hi, and thank you for the work! I made a few comments on the commit, can you have a look? Also, could you add the copyright header on all new files with your copyright line, as well as adding your copyright line to existing copyright headers in files you modified? (You should also do it in in files you modified in previous commits). Thanks!

**Comment by scribblemaniac** [comment]
I'll go through the comments momentarily. I'll fix the copyright stuff as well. It may take me a day or two for me to push the changes though, just a heads up.

**Comment by dalboris** [comment]
No worries, take your time :)

**Comment by scribblemaniac** [comment]
I got to this earlier than I thought I would. Everything should be fixed now.

**Comment by scribblemaniac** [comment]
Ah, forgot the headers, I will do that later today.

**Comment by scribblemaniac** [comment]
@dalboris Updated, everything should be ready (for real this time).

For others looking at this, I must publicly express my displeasure with having to advertise myself in the code. Dalboris and I have already discussed this at length, and he has decided that these headers are a requirement for the project. This is not what I wanted, this is not what open source means to me :disappointed:

**Comment by dalboris** [comment]
Great, thx. I'll look at this tomorrow I don't have time right now :-) I indeed require that the code contributed for the project is explicitely licensed under the MIT. I will add this in a "how to contribute" section in the README, and add a wiki page explaining while the MIT (mostly, as compared to the GPL, in your case you would prefer the other extreme ;-) )

**Comment by dalboris** [comment]
Merged, thank you again!

**Pull request merged**
