### PR TITLE
Improved timeline (again)

### PR DESCRIPTION
**Pull request by scribblemaniac**
This time I've changed the behavior for setting start and end frames, as well as left and right keyboard controls, both as agreed upon in the discussion of #4.

I have included the alternate implementations for the left and right arrow keys in comments, which will make it easier when someone decides to add it to a settings window/panel.

### CODE REVIEW

**Comment by blurymind** [comment]
do we have a command/button keyboard binding to go to previous/next
keyframe?
I find that I use that alot in other software and usually have it set up to
shift+z (previous kf) and shift+x (next kf). That way I dont have to use my
stylus hand.

**Comment by scribblemaniac** [comment]
Currently the left and right arrow keys go to the previous and next frames respectively.

I was considering proposing a change to it so that the arrow keys could be used for object translation instead. I thought that Page Up/Page Down would be a more intuitive mapping but if shift+z shift+x is fairly standard then perhaps that would be better.

**Comment by blurymind** [comment]
Left and right arrows go to previous and next frames. What would be more
useful is going to previous and next KEYframes. :)

I suggested shift+x and shift+z because they are comfortable keys for the
left hand tp change between frames while drawing with the right.
I found it to be a nice default.

Perhaps in the future we would be able to bind keys to commands?

**Comment by mottosso** [comment]
> while drawing with the right.

Unless you are left-handed. :-)

**Comment by blurymind** [comment]
Thats why these should be configurable of course :)

**Comment by scribblemaniac** [comment]
> What would be more useful is going to previous and next KEYframes. :)

Ah okay. I don't know of anything that does that right now, but I could certainly see that being done in the near future :wink: 

As for binding keys, I have no doubt that this will be a feature that is added to settings someday. For now you will simply have to change a few lines of code if you are looking for different keys. Alternatively, if you are on a Mac (and there is probably a similar feature on other operating systems) you can go to System Preferences > Keyboard > Shortcuts > App Shortcuts and then set your own shortcuts for commands that way. It's a bit more limited than modifying the code by it may be easier for people who don't know how to program or set up qt.

**Comment by dalboris** [comment]
Thx!

@blurymind To move one keyframe before/after, what about Ctrl+left/right by default? I think it's more intuitive than Shift+z/x, even though it's less convenient, I agree. In the long term, obviously, those should be configurable.

**Pull request merged**
